### ISSUE TITLE
it's possible to change sidebar width ?

### ISSUE THREAD

**Issue by reda-benhemmouche** [activeadmin-plugins/active_admin_sidebar#19]

**Comment by workgena** [comment]
Only with CSS styles. Add following style to the `app/assets/stylesheets/active_admin.css.scss`

```css
body #active_admin_content #sidebar {
    float: left;
    width: 400px;
    margin-left: -400px; /* must be equal to width(negative) */
}
```
